const glossarSidebar = {
    type: 'category',
    label: 'Glossar',
    items:[
      'hardware/sensors/bmx055',
      'hardware/sensors/co2',
      'hardware/sensors/distanz',
      'hardware/sensors/feinstaub',
      'hardware/sensors/helligkeit-uv',
      'hardware/sensors/lautstaerke',
      'hardware/sensors/luftdruck-temperatur',
      'hardware/sensors/mikro',
      'hardware/sensors/mpu6050',
      'hardware/sensors/photodiode',
      'hardware/sensors/temperatur-luftfeuchte',
      'hardware/sensors/tof',
      'hardware/sensors/truebner',
      'hardware/sensors/umweltsensor',
      'hardware/bee/bluetooth-bee',
      'hardware/bee/ethernet-bee',
      'hardware/bee/lora-bee',
      'hardware/bee/sd-bee',
      'hardware/bee/wifi-bee',
      'hardware/wifi',
      'hardware/sd',
      'hardware/accessoires/display',
      'hardware/accessoires/expander',
      'hardware/accessoires/gps',
      'hardware/accessoires/led-matrix',
      'hardware/accessoires/multiplexer',
      'hardware/accessoires/rgb-led-esp32',
      'hardware/accessoires/rgb-led',
      'hardware/accessoires/rtc-modul',
      "blockly/logik",
      "blockly/mathematik",
      "blockly/schleifen",
      "blockly/sensoren",
      "blockly/text",
      "blockly/variablen",
      "blockly/web/opensensemap",
      "blockly/zeit"
    ]
  }

export default glossarSidebar;